### ISSUE TITLE
Unsupported Cloud

### ISSUE THREAD

**Issue by jaikishantulswani** [0xsha/CloudBrute#1]
@0xsha Looks its a go version of cloud_enum, having issues after initializing like:

command : ./cloudbrute -d example.com -k example -m storage -t 80 -T 10 -w data/storage_small.txt

```
 FTL Exiting... error="unsupported cloud: "
```
Can you please let me know what goes wrong.

**Comment by 0xsha** [comment]
It means cloud provider is not supported/detected . use -c to enforce a provider . 
for example add a -c amazon  or -c google.
