### ISSUE TITLE
Panic: rutime error

### ISSUE THREAD

**Issue by daddyhack** [0xsha/CloudBrute#2]
hi. im getting the following error when running CloudBrute with the included "storage_large.txt" wordlist:

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6543ee]

my tests with the smaller wordlist complete ok. my vps has over 1GB ram still available at time of crash.

**Comment by 0xsha** [comment]
Thanks for your report . 
Please next time post full crash report,  luckily, I could reproduced  it this time, fixed in 1.0.4. 
what a nasty bug .  https://github.com/0xsha/CloudBrute/releases/tag/v1.0.4

ps : feel free to re-open if you believe issue still exists
