### ISSUE TITLE
Multi Keyword Multi Provider

### ISSUE THREAD

**Issue by jaikishantulswani** [0xsha/CloudBrute#6]
@0xsha How can we use multi keywords to search for multiple cloud providers

**Comment by honphilemon** [comment]
This an excellent tool. My issue is i downloaded the binary release on my Kali Linux I untar the file

Then move it to /usr/bin now I can't find the yaml file where am suppose to do the configuration.

Please urgent assistance is needed.thanks

**Comment by 0xsha** [comment]
@jaikishantulswani   here https://github.com/0xsha/CloudBrute/tree/master/config .

**Comment by jaikishantulswani** [comment]
@0xsha How can we use multi keywords to search for multiple cloud providers
